version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #    - "3000:3000"
  #   volumes:
  #    - .:/code
  api:
    build: api
    ports:
     - "3001:3001"
    volumes:
     - ./api:/usr/src/app